parameters:
  jobName: '' # name for each build job - needs to be unique within a given stage/pipeline

jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Import containers'
  steps:

  - download: current # download pipeline artifacts

  - task: AzureCLI@2
    displayName: 'Import container images from external registries'
    retryCountOnTaskFailure: 1
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |

        $globalInfraDeployOutput = Get-ChildItem $(Pipeline.Workspace)/terraformOutputGlobalInfra/*.json | Get-Content | ConvertFrom-JSON

        $importContainers = Get-Content ./.ado/pipelines/config/import-containers.json | ConvertFrom-JSON

        foreach ($container in $importContainers) {

          echo "Import container image $($container.image) ($($container.tag)) from $($container.registry)"
          az acr import --name $globalInfraDeployOutput.acr_name.value `
            --source "$($container.registry)/$($container.image):$($container.tag)" `
            --image "$($container.image):$($container.tag)" --force --verbose
        }
