apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity.clientid }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Chart.Name }}-identity