# Central configuration settings
# used for INT environment pipelines
variables:

# Resource prefix for this environment
- name:  'prefix'
  value: 'mcint'          # <===== CHANGE THIS! Must not be longer than 6 characters! Needs to be a unique prefix

# The first value in 'stampLocations' is the primary region used for global services.
# IMPORTANT! Changing the primary region (first value) is a BREAKING change and will destroy CosmosDB and Front Door.
- name: 'stampLocations'
  value: '["swedencentral", "uksouth"]' # Check which regions are valid. There is a list in /src/infra/README.md

- name: 'stampLocationsGrafana'
  value: '["eastus"]' # Check which regions are valid. There is a list in /src/infra/README.md
- name: 'grafanaAccessGroupId'
  value: '952ad759-6673-4d83-917e-136f2b7e1594' # aad group id that grants access to login into grafana

# Terraform state variables
- name:  'terraformResourceGroup'
  value: 'terraformstate-rg'        # <===== CHANGE THIS VALUE IF NEEDED
- name:  'terraformStorageAccount'
  value: '$(prefix)tfstatestore'  # Needs to be a globally unique name

# Custom DNS name settings
- name: 'envDnsZoneRG'
  value: 'mc-dnszones-rg'                # <===== CHANGE THIS OR LEAVE THE VALUE BLANK
- name: 'envDomainName'
  value: 'int.shop.mission-critical.app'   # <===== CHANGE THIS OR LEAVE THE VALUE BLANK

# Other settings
- name:  'contactEmail'
  value: 'noreply@microsoft.com'  # <===== CHANGE THIS VALUE TO ONE OF YOUR REAL EMAIL ADDRESSES (OR A GROUP)!